/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_lenguaje_ii;

import java.util.ArrayList;

/**
 *
 * @author ulises
 */
public class w_coleccion extends javax.swing.JFrame {
        String rutaColeccion = "";
        String rutaUsuarios = "";
        String rutaFiguritas = "";

        // Listas en memoria RAM
        ArrayList<ColeccionFigurita> estructura_coleccion = new ArrayList<>();
        ArrayList<Usuario> estructura_usuarios = new ArrayList<>();
        ArrayList<Figurita> estructura_figuritas = new ArrayList<>();   

    /**
     * Creates new form w_coleccion
     */
    public w_coleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            org.ini4j.Wini ini = new org.ini4j.Wini(new java.io.File("configuracion.ini"));
            rutaColeccion = ini.get("Archivos", "coleccion");
            rutaUsuarios = ini.get("Archivos", "usuarios");
            rutaFiguritas = ini.get("Archivos", "figuritas");
            LeerDatos_usuarios();
            LeerDatos_figuritas();
            LeerDatos_coleccion();
            
            CargarComboUsuarios();
            CargarComboFiguritas();
            MostrarDatos_coleccion();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(null, "Error al iniciar Colección: " + e.getMessage());
}
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        cmbFiguritas = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGrabarCol = new javax.swing.JButton();
        btnAtrasCol = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaColeccion = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbFiguritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIENE", "FALTA" }));

        btnGrabarCol.setText("Grabar");
        btnGrabarCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarColActionPerformed(evt);
            }
        });

        btnAtrasCol.setText("Atras");
        btnAtrasCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasColActionPerformed(evt);
            }
        });

        tablaColeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaColeccion);

        jLabel2.setText("Usuarios");

        jLabel3.setText("Figurita a agregar: ");

        jLabel4.setText("Estado de la Figurita: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(cmbFiguritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(460, 460, 460))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnGrabarCol))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtrasCol)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGrabarCol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiguritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnAtrasCol)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasColActionPerformed
        // TODO add your handling code here:
        w_principal menu = new w_principal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasColActionPerformed

    private void btnGrabarColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarColActionPerformed
        // TODO add your handling code here:
        // Validación dentro del botón Grabar
        if (cmbFiguritas.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, selecciona una figurita válida de la lista.", 
                    "Campo Vacío", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        return;// Frena el guardado
        }
        
        try {
            
        // 2. Capturamos los datos limpios de los combos
        String usuarioSeleccionado = cmbUsuarios.getSelectedItem().toString().split(" - ")[0];
        String figuritaSeleccionada = cmbFiguritas.getSelectedItem().toString().split(" - ")[0];
        String estadoSeleccionado = cmbEstado.getSelectedItem().toString();
        
        // Generamos un ID automático para este registro (ej: COL-1718293)
        String idAutomatico = "COL-" + System.currentTimeMillis(); 
        String cantidadPorDefecto = "1";

        // 3. Creamos el objeto usando el constructor de tus compañeros (imagen image_9f0145.png)
        ColeccionFigurita nuevaColeccion = new ColeccionFigurita(
            idAutomatico, 
            usuarioSeleccionado, 
            figuritaSeleccionada, 
            estadoSeleccionado, 
            cantidadPorDefecto
        );

        // 4. Agregamos a la lista de la RAM
        estructura_coleccion.add(nuevaColeccion);

        // 5. Guardamos en el archivo (Persistencia)
        java.io.File archivo = new java.io.File(rutaColeccion);
        java.io.FileOutputStream fos = new java.io.FileOutputStream(archivo);
        java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
        oos.writeObject(estructura_coleccion);
        oos.close();
        fos.close();

        // 6. Refrescamos la tabla visual
        MostrarDatos_coleccion();

        // 7. Mensaje de éxito
        javax.swing.JOptionPane.showMessageDialog(this, "¡Figurita registrada en tu colección con éxito!");
        cmbFiguritas.setSelectedIndex(0); 

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnGrabarColActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(w_coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(w_coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(w_coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(w_coleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new w_coleccion().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasCol;
    private javax.swing.JButton btnGrabarCol;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFiguritas;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaColeccion;
    // End of variables declaration//GEN-END:variables
    public void LeerDatos_usuarios() {
    try {
        java.io.File archivo = new java.io.File(rutaUsuarios);
        if (archivo.exists()) {
            java.io.FileInputStream fis = new java.io.FileInputStream(archivo);
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            estructura_usuarios = (ArrayList<Usuario>) ois.readObject();
            ois.close(); fis.close();
        }
    } catch (Exception e) { System.out.println("Error usuarios: " + e.getMessage()); }
}

public void LeerDatos_figuritas() {
    try {
        java.io.File archivo = new java.io.File(rutaFiguritas);
        if (archivo.exists()) {
            java.io.FileInputStream fis = new java.io.FileInputStream(archivo);
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            estructura_figuritas = (ArrayList<Figurita>) ois.readObject();
            ois.close(); fis.close();
        }
    } catch (Exception e) { System.out.println("Error figuritas: " + e.getMessage()); }
}

public void LeerDatos_coleccion() {
    try {
        java.io.File archivo = new java.io.File(rutaColeccion);
        if (archivo.exists()) {
            java.io.FileInputStream fis = new java.io.FileInputStream(archivo);
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            estructura_coleccion = (ArrayList<ColeccionFigurita>) ois.readObject();
            ois.close(); fis.close();
        }
    } catch (Exception e) { System.out.println("Error coleccion: " + e.getMessage()); }
}

public void CargarComboUsuarios() {
    cmbUsuarios.removeAllItems();
    for (Usuario u : estructura_usuarios) {
        cmbUsuarios.addItem(u.getId() + " - " + u.getNombre());
    }
}

public void CargarComboFiguritas() {
    cmbFiguritas.removeAllItems();
    
    cmbFiguritas.addItem("--- Busca tu figurita ---");
    
    for (Figurita f : estructura_figuritas) {
        String id = f.getId().contains("jTextField") ? "ID" : f.getId();
        String numero = f.getNumero().contains("jTextField") ? "0" : f.getNumero();
        String tipo = f.getTipo().contains("jTextField") ? "Común" : f.getTipo();
        
        // Las agregamos abajo del buscador
        cmbFiguritas.addItem(id + " - Núm: " + numero + " (" + tipo + ")");
    }
}


public void MostrarDatos_coleccion() {
    // 1. Definimos las columnas de la tabla de colecciones
    String[] columnas = {"Usuario", "Figurita (ID)", "Estado"};
    
    // 2. Creamos el modelo de la tabla (haciendo que las celdas no sean editables con el doble clic)
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    // 3. Recorremos la lista en memoria y cargamos las filas
    for (ColeccionFigurita col : estructura_coleccion) {
        Object[] fila = {
            col.getUsuarioId(),   // ID o nombre del usuario
            col.getFiguritaId(),  // ID de la figurita
            col.getEstado()       // "TIENE" o "FALTA"
        };
        modelo.addRow(fila);
    }
    
    // 4. Le pasamos el modelo a tu componente visual Tabla
    // (Asegurate de que tu tabla en el Design se llame exacto 'tablaColeccion')
    tablaColeccion.setModel(modelo); 
}
}
