/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_lenguaje_ii;

import java.io.File;
import java.util.ArrayList;
import org.ini4j.Wini;

/**
 *
 * @author ulises
 */
public class w_figurita extends javax.swing.JFrame {
    String rutaFiguritas;
    String rutaJugadores; //Para el combo box we
    
    //La memoria temporal donde estara la info
    ArrayList<Figurita> estructura_figuritas = new ArrayList<>();
    ArrayList<Jugador> estructura_jugadores = new ArrayList<>();
    
    public w_figurita() {
        initComponents();
        
        try {
            Wini ini = new Wini(new File("configuracion.ini"));
            rutaFiguritas = ini.get("Archivos", "figuritas");
            rutaJugadores = ini.get("Archivos", "jugadores");
            
            //Las tareas de arranque chango
            this.LeerDatos_figurita();
            this.LeerDatos_jugadores();
            this.CargarComboJugador();
            this.MostrarDatos_figurita();
            
        } catch (Exception e) {
            //Esto es en caso de errores, onda si sale mal pues te salta a esta parte del codigo
            javax.swing.JOptionPane.showMessageDialog(null, "Error al iniciar configuraciones: " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbJugadores = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFiguritas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        txtId.setColumns(10);
        txtId.setText("Ingresa el ID...");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero: ");

        jLabel3.setText("Tipo: ");

        txtNumero.setColumns(10);
        txtNumero.setText("Ingresa el numero...");

        txtTipo.setColumns(10);
        txtTipo.setText("Ingrese el tipo..\n");

        jLabel4.setText("Jugador:");

        cmbJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNuevo.setText("Nuevo");

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        tablaFiguritas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFiguritas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGrabar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGrabar))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
        
        this.Agregar_figurita();
        this.GrabarDatos_figurita();
        
        this.MostrarDatos_figurita();
        this.LimpiarCampos();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(w_figurita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(w_figurita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(w_figurita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(w_figurita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new w_figurita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFiguritas;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
    public void LeerDatos_jugadores() {
        //Este es el metodo de leer datos de jogadores manito
    try {
        java.io.File archivo = new java.io.File(rutaJugadores);
        if (archivo.exists()) {
            java.io.FileInputStream fis = new java.io.FileInputStream(archivo);
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            
            // Leemos el archivo completo de los jogadores
            estructura_jugadores = (ArrayList<Jugador>) ois.readObject();
            
            ois.close();
            fis.close();
        }
    } catch (Exception e) {
        System.out.println("Error al leer jugadores: " + e.getMessage());
    }
}

public void LeerDatos_figurita() {
    //El metodo de leer datos de figuritas
    try {
        java.io.File archivo = new java.io.File(rutaFiguritas);
        if (archivo.exists()) {
            java.io.FileInputStream fis = new java.io.FileInputStream(archivo);
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            
            // Leemos el archivo de tus figuritas
            estructura_figuritas = (ArrayList<Figurita>) ois.readObject();
            
            ois.close();
            fis.close();
        }
    } catch (Exception e) {
        System.out.println("Error al leer figuritas: " + e.getMessage());
    }
}

public void CargarComboJugador() {
    // 1. Limpiamos el combo box, onda que no haya opciones
    cmbJugadores.removeAllItems();
    
    // 2. Recorremos la lista de jugadores de la memoria
    for (Jugador j : estructura_jugadores) {
        // 3. Agregamos el ID y Nombre al combo box
        cmbJugadores.addItem(j.getId() + " - " + j.getNombre());
    }
}
public void MostrarDatos_figurita() {
    // 1. Creamos el modelo de la tabla 
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
    
    // 2. Le definimos los nombres de las columnas que queremos ver, mango mango mango
    modelo.addColumn("ID");
    modelo.addColumn("Número");
    modelo.addColumn("Tipo");
    modelo.addColumn("ID Jugador");
    
    // 3. Recorremos nuestra lista de figuritas en memoria
    for (Figurita f : estructura_figuritas) {
        // Creamos una fila de texto con los datos de la figurita
        String[] fila = new String[4];
        fila[0] = f.getId();
        fila[1] = f.getNumero();
        fila[2] = f.getTipo();
        fila[3] = f.getJugadorId();
        
        // Agregamos la fila al modelo
        modelo.addRow(fila);
    }
    
    // 4. Le decimos a nuestra tabla visual que use este modelo con datos
    tablaFiguritas.setModel(modelo);
}
//Toma los datos de la pantalla y los mete a la lista en la RAM
public void Agregar_figurita() {
    
    //Esto e' una validacion papi, onda si no hay nada te dice: "Stop son of the bitch"
    if (this.txtId.getText().trim().isEmpty() || 
        this.txtNumero.getText().trim().isEmpty() || 
        this.txtTipo.getText().trim().isEmpty()) {
        
        // Si falta algo, mostramos el cartel de advertencia
        javax.swing.JOptionPane.showMessageDialog(null, 
            "Por favor, complete todos los campos (ID, Número y Tipo) antes de grabar.", 
            "Campos incompletos", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        
        return; // Este 'return' corta el método acá; no deja que el código siga hacia abajo
    }
    
    // Si pasó la validación, recién ahí crea y guarda la figurita.
    Figurita f = new Figurita("", "", "", "");
    f.setId(this.txtId.getText());
    f.setNumero(this.txtNumero.getText());
    f.setTipo(this.txtTipo.getText()); 

    // Del ComboBox tomamos solo el ID del jugador
    if (cmbJugadores.getSelectedItem() != null) {
        String jugadorSeleccionado = cmbJugadores.getSelectedItem().toString();
        f.setJugadorId(jugadorSeleccionado.split(" - ")[0]);
    }

    estructura_figuritas.add(f);
    javax.swing.JOptionPane.showMessageDialog(null, "Figurita agregada correctamente");
}

//Agarra la lista de la RAM y la guarda en el archivo físico .txt 
public void GrabarDatos_figurita() {
    try {
        java.io.File archivo = new java.io.File(rutaFiguritas);
        java.io.FileOutputStream fos = new java.io.FileOutputStream(archivo);
        java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
        
        oos.writeObject(estructura_figuritas); // Guarda la lista completa de golpe
        
        oos.close();
        fos.close();
    } catch (Exception e) {
        System.out.println("Error al grabar figuritas: " + e.getMessage());
    }
}
public void LimpiarCampos() {
    //Esto es para que cada vez que se guarda una figu, despues se borre lo ultimo asi tenga todo vacio para la siguiente figu
    this.txtId.setText("");
    this.txtNumero.setText("");
    this.txtTipo.setText("");
    if (cmbJugadores.getItemCount() > 0) {
        cmbJugadores.setSelectedIndex(0); // Vuelve el combo box al primer elemento
    }
}
}

