/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lenguaje_ii;

/**
 *
 * @author gabiz
 */
public class w_principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(w_principal.class.getName());

    /**
     * Creates new form w_principal
     */
    public w_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        btnLeyenda = new javax.swing.JButton();
        btnEstadio = new javax.swing.JButton();
        btnJugador = new javax.swing.JButton();
        btnFigurita = new javax.swing.JButton();
        btnColeccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Figuritas - Mundial 2026");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnSeleccion.setText("Selecciones");
        btnSeleccion.addActionListener(this::btnSeleccionActionPerformed);

        btnLeyenda.setText("Leyendas");
        btnLeyenda.addActionListener(this::btnLeyendaActionPerformed);

        btnEstadio.setText("Estadios");
        btnEstadio.addActionListener(this::btnEstadioActionPerformed);

        btnJugador.setText("Jugadores");
        btnJugador.addActionListener(this::btnJugadorActionPerformed);

        btnFigurita.setText("Figuritas");
        btnFigurita.addActionListener(this::btnFiguritaActionPerformed);

        btnColeccion.setText("Mi Coleccion");
        btnColeccion.addActionListener(this::btnColeccionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeleccion)
                            .addComponent(btnUsuarios)
                            .addComponent(btnLeyenda)
                            .addComponent(btnEstadio)
                            .addComponent(btnJugador)
                            .addComponent(btnFigurita)
                            .addComponent(btnColeccion))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLeyenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFigurita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColeccion)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // new w_usuarios().setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        // new w_seleccion().setVisible(true);
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void btnLeyendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeyendaActionPerformed
        new w_leyendas().setVisible(true);
    }//GEN-LAST:event_btnLeyendaActionPerformed

    private void btnEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadioActionPerformed
        // new w_estadio().setVisible(true);
    }//GEN-LAST:event_btnEstadioActionPerformed

    private void btnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorActionPerformed
        // new w_jugador().setVisible(true);
    }//GEN-LAST:event_btnJugadorActionPerformed

    private void btnFiguritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiguritaActionPerformed
        // new w_figurita().setVisible(true);
    }//GEN-LAST:event_btnFiguritaActionPerformed

    private void btnColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColeccionActionPerformed
        // new w_coleccion().setVisible(true);
    }//GEN-LAST:event_btnColeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new w_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColeccion;
    private javax.swing.JButton btnEstadio;
    private javax.swing.JButton btnFigurita;
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnLeyenda;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
